/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // ---- Editorial brand palette (public site) ----
        // High-fashion "L'Atelier d'Artiste" system: warm paper canvas,
        // architectural onyx, velvet burgundy and antique-gold ornament.
        'pearl-white': '#F8F4F0',
        'onyx-black': '#1A1A1A',
        'deep-burgundy': '#4A0404',
        'antique-gold': '#B58D3D',
        canvas: '#FCF9F8',
        ink: '#1C1B1B',
        'ink-soft': '#554240',
        line: '#DCC0BD',
        'line-strong': '#89726F',
        'gold-soft': '#C9A86A',

        // ---- Admin palette (dark panel, kept from the base) ----
        'surface-container': '#201f1f',
        'tertiary-container': '#e4e2e1',
        'pure-black': '#000000',
        'outline-variant': '#444748',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        surface: '#131313',
        'surface-container-high': '#2a2a2a',
        primary: '#ffffff',
        background: '#131313',
        'primary-container': '#e2e2e2',
        secondary: '#c8c6c5',
        'on-background': '#e5e2e1',
        'on-surface-variant': '#c4c7c8',
        'surface-container-highest': '#353534',
        'silver-gray': '#A1A1A1',
        'secondary-container': '#474746',
        'status-gold': '#C5A059',
        'on-primary': '#2f3131',
        outline: '#8e9192',
        'surface-container-low': '#1c1b1b',
        'surface-tint': '#c6c6c7',
        'surface-container-lowest': '#0e0e0e',
        'surface-dim': '#131313',
        'on-surface': '#e5e2e1',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        tertiary: '#ffffff',
        'surface-variant': '#353534',
        'surface-bright': '#3a3939',
      },
      borderRadius: {
        // Sharp, architectural edges per the editorial system.
        DEFAULT: '0px',
        sm: '0px',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        gutter: '40px',
        'safe-margin': '80px',
        'safe-margin-mobile': '24px',
        'section-gap': '160px',
        // legacy tokens still referenced by the admin panel
        'margin-desktop': '80px',
        'margin-mobile': '20px',
        'margin-tablet': '40px',
      },
      fontFamily: {
        // EB Garamond = the "Artiste" (monumental headlines/display).
        'display-xl': ['"EB Garamond"', 'serif'],
        'headline-lg': ['"EB Garamond"', 'serif'],
        'headline-lg-mobile': ['"EB Garamond"', 'serif'],
        'headline-md': ['"EB Garamond"', 'serif'],
        // Montserrat = the "Atelier" (precise, modernist UI/labels/body).
        'body-lg': ['Montserrat', 'sans-serif'],
        'body-md': ['Montserrat', 'sans-serif'],
        'nav-item': ['Montserrat', 'sans-serif'],
        'label-caps': ['Montserrat', 'sans-serif'],
        'label-sm': ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['120px', { lineHeight: '110px', letterSpacing: '-0.04em', fontWeight: '400' }],
        'headline-lg': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-lg-mobile': ['40px', { lineHeight: '48px', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '32px', letterSpacing: '0.01em', fontWeight: '300' }],
        'body-md': ['15px', { lineHeight: '26px', fontWeight: '400' }],
        'nav-item': ['12px', { lineHeight: '16px', letterSpacing: '0.15em', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.2em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
